### ISSUE TITLE
Alarm continues to sound

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/DangIt#4]
When I switch from my map view back to my vessel it beeps even tho there is nothing broken on it, it starts when something broke on a different vessel and persists across all vessels until I restart KSP, is there a fix for this that I am missing, any help would be greatly appreciated, I love this mod :) just wanna see if I can correct this issue.

**Comment by thelapisfox** [comment]
I am having this same issue. Tried turning the volume all the way down and even turned off the alarm options. None of the options worked. The only thing that worked, was turning Master Volume to 0, even messing with the other game volume options had no effect on the alarm volume. Tried to rename the sound file to prevent playback of sound due to this issue but this only flooded the console with errors. Finally, I went into Audacity and modified the sound so much, it will be almost mute.

**Comment by linuxgurugamer** [comment]
Is this a continous sound, or just a few seconds beeping when switching vessels?

**Comment by jbaker0428** [comment]
I've had this happen many times as well. When it happens, I get the single-play ~4x beep every time I close the map view in flight. I deleted the ogg file entirely to work around it.

**Comment by linuxgurugamer** [comment]
Can you try the latest version (for 1.3) please?  I've revamped some of the internal code, and while it hasn't happened for me yet, I haven't played enough to be sure

**Comment by jbaker0428** [comment]
I have seen it once on KSP 1.3 and Dangit 0.7.13.1

**Comment by SynthWeaver** [comment]
I had this bug on 1.3.1

**Comment by linuxgurugamer** [comment]
Fixed in 0.7.18.0
